# Generated by Django 2.2.10 on 2020-04-01 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import js_color_picker.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseContainer',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='js_showcase_showcasecontainer', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ShowcaseSlideshow',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='js_showcase_showcaseslideshow', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anchor title')),
                ('layout', models.CharField(blank=True, default='', max_length=60, verbose_name='layout')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ShowcaseSlide',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='js_showcase_showcaseslide', serialize=False, to='cms.CMSPlugin')),
                ('percentage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Percentage appears')),
                ('fade_in', models.BooleanField(default=False, verbose_name='Fade In')),
                ('fade_out', models.BooleanField(default=False, verbose_name='Fade Out')),
                ('landscape_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Landscape Image')),
                ('portrait_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Portrait Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ShowcaseSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='js_showcase_showcasesection', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anchor title')),
                ('background_color', js_color_picker.fields.RGBColorField(blank=True, colors={'#0073CF': 'Blue 2', '#00B0CA': 'Blue 1', '#00ae65': 'green', '#0D2240': 'dark-blue', '#4d4d4d': 'grey', '#5E6A71': 'dark-grey', '#67B2E8': 'pale-blue', '#808080': 'middle-grey', '#C3009E': 'Purple', '#CAD7E6': 'Light 2', '#D1EAEC': 'Light 1', '#E00034': 'Dark red', '#E1F0FA': 'palest-blue', '#E8CFDC': 'Light purple', '#F0AB00': 'Dark yellow', '#F7D1C2': 'Light red', '#FEEDCA': 'Light yellow', '#ccc': 'light-grey', '#eee': 'lightest-grey'}, mode='choice', null=True, verbose_name='Background Color')),
                ('layout', models.CharField(blank=True, default='', max_length=60, verbose_name='layout')),
                ('background_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Background Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
