# Generated by Django 2.2.10 on 2020-04-22 04:26

from django.db import migrations, models
import django.db.models.deletion
import js_showcase.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('js_showcase', '0003_auto_20200415_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseArticle',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='js_showcase_showcasearticle', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('layout', models.CharField(blank=True, default='', max_length=60, verbose_name='layout')),
                ('attributes', js_showcase.models.AttributesField(blank=True, default=dict, verbose_name='Attributes')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
