# Generated by Django 2.2.10 on 2020-04-22 04:26

from django.db import migrations, models
import django.db.models.deletion
import js_showcase.models


class Migration(migrations.Migration):

    dependencies = [
        ('js_showcase', '0004_showcasearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaseslide',
            name='layout',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='layout'),
        ),
    ]
