# Generated by Django 2.2.12 on 2020-09-08 13:51

from django.db import migrations, models
import js_color_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_showcase', '0005_showcaseslide_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaseslideshow',
            name='lg_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showcaseslideshow',
            name='md_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showcaseslideshow',
            name='sm_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showcaseslideshow',
            name='xl_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showcaseslideshow',
            name='xs_hide',
            field=models.BooleanField(default=False),
        ),
    ]
