# Generated by Django 2.2.12 on 2020-10-05 11:22

from django.db import migrations, models
import js_color_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_showcase', '0006_auto_20200908_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasesection',
            name='lg_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showcasesection',
            name='md_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showcasesection',
            name='sm_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showcasesection',
            name='xl_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showcasesection',
            name='xs_hide',
            field=models.BooleanField(default=False),
        ),
    ]
