# Generated by Django 2.2.12 on 2020-10-16 08:09

from django.db import migrations, models
import js_color_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_showcase', '0007_auto_20201005_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasecontainer',
            name='layout',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='layout'),
        ),
    ]
